#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'types.pb'; rescue LoadError; end

module PolarData
  # forward declarations
  class PbIdentifier < ::ProtocolBuffers::Message; end

  class PbIdentifier < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbIdentifier"

    required :uint64, :ecosystem_id, 1
    required ::PbSystemDateTime, :created, 2
    required ::PbSystemDateTime, :last_modified, 3
    optional :bool, :deleted, 4
  end

end
