#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'types.pb'; rescue LoadError; end

module PolarData
  # forward declarations
  class PbSyncInfo < ::ProtocolBuffers::Message; end

  class PbSyncInfo < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbSyncInfo"

    required ::PbSystemDateTime, :last_modified, 1
    repeated :string, :changed_path, 2
    optional ::PbSystemDateTime, :last_synchronized, 3
    optional :bool, :full_sync_required, 4, :default => true
  end

end
